# -*- coding: utf-8 -*-
"""CalculadoraSimples4Operações.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YHkR5I17MqANHzb8CMN5nnaZ7_nSvu7i
"""

n1 = float(input("Digite o primeiro número: "))
n2 = float(input("Digite o segundo número: "))
operacao = input("Qual operação deseja realizar? ")


if operacao == 'Soma':
    print('O resultado da soma entre esses dois numeros é de: ',n1 + n2)
elif operacao == 'Subtração':
    print('O resultado da subtração entre esses dois numeros é de: ', n1 - n2)
elif operacao == 'Multiplicação':
    print('O resultado da soma entre esses dois numeros é de:', n1 * n2)
elif operacao == 'Divisão':
    print('O resultado da soma entre esses dois numeros é de:', n1 / n2)
else:
    print('Operação inválida!')